import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        id="nurix-widget"
        src="https://d3udl6i7sipqjw.cloudfront.net/dev/webwidget/chat.js"
        type="module"
        data-api-key="dcc297b803f4724984f64736c93cfd2"
        data-widget-id="265"
        data-controller="nurix"
        data-chat-btn-bottom-mobile="10px"
        data-gateway-api-key="1234567890"
        strategy="afterInteractive"
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div id="nurix-widget"></div>
      </body>
    </html>
  );
}
